### ISSUE TITLE
Simple mesh edits

### ISSUE THREAD

**Issue by krips89** [qnzhou/PyMesh#17]
Suppose I want to add translate a mesh by 1, 1, 1.

So the simplest way which I thought would work is:
```
mesh = pymesh.load_mesh(objfile)
mesh.vertices += 1
```

But this does not work. It shows:

`AttributeError: can't set attribute`

What is the easiest (or the possible) ways of updating vertices or faces of a mesh?

**Comment by qnzhou** [comment]
First, a word of caution.  Each mesh is potentially bundled with vertex/face attributes (normal, area, curvature, etc.), which may become invalid once vertices and faces are changed.

The safe way of doing it is to extract the vertices, update it and form a new mesh:

```
mesh = pymesh.load_mesh(objfile)
vertices = mesh.vertices;
vertices += 1;
new_mesh = pymesh.form_mesh(vertices, mesh.faces)
```

This creates a brand new mesh with vertices translated and leave the old mesh intact.  On the other hand, it is possible (but not recommended) to update mesh vertices directly:

```
mesh.vertex_ref = mesh.vertices + 1
```
It is not recommended because it is not thoroughly tested, and it is now user's responsibility to update/recompute any geometry attributes.

Hope it helps!

**Comment by krips89** [comment]
Thanks, I had already found the `form_mesh` function. By the way, assignment to `mesh.vertex_ref` does not work as well.
